import { Share, Platform } from 'react-native';
import RNPrint from 'react-native-print';
import { authService } from './auth.service';
import { HealthHistoryData } from './firestore.service';
import { HealthEntry } from '../components/health/types';

interface PDFExportService {
  generateHealthReportHTML: (healthData: HealthHistoryData, userName?: string) => string;
  exportToPDF: (healthData: HealthHistoryData) => Promise<void>;
}

const HEALTH_METRIC_LABELS: { [key: string]: { label: string; unit?: string } } = {
  weight: { label: 'Weight', unit: 'kg' },
  sleepHours: { label: 'Sleep Hours', unit: 'hours' },
  waterIntake: { label: 'Water Intake', unit: 'L' },
  bloodPressure: { label: 'Blood Pressure', unit: '' },
  pulse: { label: 'Heart Rate', unit: 'bpm' },
  bloodSugar: { label: 'Blood Sugar', unit: 'mg/dL' },
  temperature: { label: 'Body Temperature', unit: '°C' },
  steps: { label: 'Daily Steps', unit: 'steps' },
  calories: { label: 'Calories Burned', unit: 'kcal' },
  exercise: { label: 'Exercise', unit: '' },
  mood: { label: 'Mood', unit: '' },
  period: { label: 'Menstrual Cycle', unit: '' },
  symptoms: { label: 'Symptoms', unit: '' },
  medications: { label: 'Medications', unit: '' },
};

class PDFExportServiceImpl implements PDFExportService {
  generateHealthReportHTML(healthData: HealthHistoryData, userName?: string): string {
    const user = authService.getCurrentUser();
    const name = userName || user?.displayName || user?.email || 'Patient';
    const currentDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 20px;
      color: #333;
    }
    .header {
      text-align: center;
      margin-bottom: 30px;
      border-bottom: 3px solid #9333ea;
      padding-bottom: 20px;
    }
    .header h1 {
      color: #9333ea;
      margin: 0;
      font-size: 28px;
    }
    .header p {
      color: #666;
      margin: 5px 0;
    }
    .section {
      margin-bottom: 25px;
      page-break-inside: avoid;
    }
    .section-title {
      background-color: #f3f4f6;
      padding: 12px;
      font-weight: bold;
      font-size: 18px;
      color: #1f2937;
      border-left: 4px solid #9333ea;
      margin-bottom: 10px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 15px;
    }
    th {
      background-color: #9333ea;
      color: white;
      padding: 10px;
      text-align: left;
      font-weight: bold;
    }
    td {
      padding: 8px 10px;
      border-bottom: 1px solid #e5e7eb;
    }
    tr:nth-child(even) {
      background-color: #f9fafb;
    }
    .no-data {
      color: #9ca3af;
      font-style: italic;
      padding: 10px;
    }
    .footer {
      margin-top: 40px;
      text-align: center;
      color: #6b7280;
      font-size: 12px;
      border-top: 1px solid #e5e7eb;
      padding-top: 20px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>MedInfera Health Report</h1>
    <p><strong>Patient:</strong> ${name}</p>
    <p><strong>Report Date:</strong> ${currentDate}</p>
  </div>
`;

    // Her sağlık metrik kategorisi için tablo oluştur
    Object.keys(healthData).forEach((key) => {
      const entries = healthData[key as keyof HealthHistoryData];
      const config = HEALTH_METRIC_LABELS[key];
      
      if (!config) return;

      html += `
  <div class="section">
    <div class="section-title">${config.label}</div>
`;

      if (entries && entries.length > 0) {
        html += `
    <table>
      <thead>
        <tr>
          <th>Date & Time</th>
          <th>Value${config.unit ? ` (${config.unit})` : ''}</th>
        </tr>
      </thead>
      <tbody>
`;

        // En yeni kayıtlar önce gelsin
        const sortedEntries = [...entries].reverse();
        sortedEntries.forEach((entry: HealthEntry) => {
          html += `
        <tr>
          <td>${entry.date}</td>
          <td>${entry.value}</td>
        </tr>
`;
        });

        html += `
      </tbody>
    </table>
`;
      } else {
        html += `
    <div class="no-data">No data recorded for this metric</div>
`;
      }

      html += `
  </div>
`;
    });

    html += `
  <div class="footer">
    <p>This report was generated by MedInfera Health App</p>
    <p>For medical use only - Please consult with your healthcare provider</p>
  </div>
</body>
</html>
`;

    return html;
  }

  async exportToPDF(healthData: HealthHistoryData): Promise<void> {
    try {
      const user = authService.getCurrentUser();
      const userName = user?.displayName || user?.email || 'Patient';
      
      // HTML içeriği oluştur
      const htmlContent = this.generateHealthReportHTML(healthData, userName);

      // Print seçenekleri
      const printOptions = {
        html: htmlContent,
        fileName: `MedInfera_Health_Report_${userName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}`,
        base64: false,
        width: 595, // A4 width in points
        height: 842, // A4 height in points
      };

      // Print dialog'u aç
      await RNPrint.print(printOptions);
    } catch (error: any) {
      // Print başarısız olursa Share API'ye geri dön
      try {
        const user = authService.getCurrentUser();
        const userName = user?.displayName || user?.email || 'Patient';
        
        if (Platform.OS === 'ios') {
          await Share.share({
            message: `MedInfera Health Report for ${userName}\n\n${this.formatHealthDataAsText(healthData, userName)}`,
            title: 'Health Report',
          });
        } else {
          await Share.share({
            message: `MedInfera Health Report\n\n${this.formatHealthDataAsText(healthData, userName)}`,
            title: 'Health Report',
          });
        }
      } catch {
        throw new Error(`Failed to export health report: ${error.message}`);
      }
    }
  }

  private formatHealthDataAsText(healthData: HealthHistoryData, userName: string): string {
    const currentDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    let text = `MEDINFERA HEALTH REPORT\n`;
    text += `Patient: ${userName}\n`;
    text += `Report Date: ${currentDate}\n`;
    text += `\n${'='.repeat(50)}\n\n`;

    Object.keys(healthData).forEach((key) => {
      const entries = healthData[key as keyof HealthHistoryData];
      const config = HEALTH_METRIC_LABELS[key];
      
      if (!config) return;

      text += `${config.label}${config.unit ? ` (${config.unit})` : ''}:\n`;
      
      if (entries && entries.length > 0) {
        const sortedEntries = [...entries].reverse();
        sortedEntries.forEach((entry: HealthEntry) => {
          text += `  - ${entry.date}: ${entry.value}\n`;
        });
      } else {
        text += `  No data recorded\n`;
      }
      
      text += `\n`;
    });

    text += `\n${'='.repeat(50)}\n`;
    text += `This report was generated by MedInfera Health App\n`;
    text += `For medical use only - Please consult with your healthcare provider`;

    return text;
  }
}

export const pdfExportService = new PDFExportServiceImpl();

